### ISSUE TITLE
Where is the right file???

### ISSUE THREAD

**Issue by ryanNewcodeer123** [ComlanGiovanni/Tic-Tac-Toe_in_Csharp#2]
HI, I am a beginner, and I just found your project online and it looks great, I want to copy it, but I can't find a suitable file for the main program. Can you help?

**Comment by ComlanGiovanni** [comment]
👋 Helloooo, thanks for looking at this project, you can found the entry point in Tic-Tac-Toe/Program.cs this a the main over there.
long time i did not touch this project, i will probably take a look again and complete it because there is a few people forking a staring it XD.
dont hesitate if you have some pull request or any other question !
